/* Generated by scripts/refresh-data.py. */
import type { Snapshot } from "@/lib/types";
import data2024 from "./2024.json";
import data2026 from "./2026.json";
export const datasets: Record<number, Snapshot> = {
  2024: data2024,
  2026: data2026,
};
